### ISSUE TITLE
Vote on wrong video

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#15]
![image](https://user-images.githubusercontent.com/1332279/68855389-7b2bba80-0721-11ea-8115-150a728f707f.png)

In this state, when I click the voting button on 3rd video,

![image](https://user-images.githubusercontent.com/1332279/68855406-82eb5f00-0721-11ea-9455-947cd6cb6837.png)

The second one gets voted

**Comment by sydneyitguy** [comment]
Oh it was actually the 3rd one gets voted and re-sorted.. lol
Yeah that's confusing.
The sorting should not be changed when user clicks voting. It should be changed on page refresh.

**Comment by ggomaeng** [comment]
Yeah it was confusing, so I thought about adding a slide animation, but I agree with you. Will go with #1 for now.
