### ISSUE TITLE
Previous section

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#26]
Oh it seems we forgot you add prev days sections under the Today's section

Behaviour:
- [x] Today section (days_ago=0&top=false)
- [x] Yesterday: `days_ago=1&top=true` by default `top=false` when [Show more] button is clicked (replace the list)

Title:
- [x] 2 days ago - 7 days ago: Title should be weekdays. e.g. Thursday, Wednesday..) / From last week post - Show like "November 5th"

Here is the title generation code I copied from Steemhunt:
```javascript
function daysAgoToString(daysAgo) {
  if (daysAgo === 0) {
    return 'Today';
  }
  if (daysAgo === 1) {
    return 'Yesterday'
  }
  const date = new Date(new Date() - 86400000 * daysAgo);
  // Return weekday if less than a week
  if (daysAgo < 7) {
    const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    return weekdays[date.getDay()];
  }
  return moment(date).format('MMMM Do');
}
````

**Comment by ggomaeng** [comment]
So the list should behave as an infinite list, right -- not only for this week?

**Comment by ggomaeng** [comment]
Should we implement it in an infinite scroll way such that it loads automatically at the end?

**Comment by sydneyitguy** [comment]
Yeah I guess infinite scroll is better than "LOAD PREVIOUS DAY",
especially when there's "SHOW MORE FROM THIS DAY" link too.

We can just make that "SHOW MORE" and use infinite scrolls for the daily buckets
We can handle infinite loading by..
- [ ] When there's no items on a day, try the next day until it returns no items for 10 consecutive days

**Comment by sydneyitguy** [comment]
Closing this issue in favor of #46
