### ISSUE TITLE
Weird duplication of video list

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#27]
![image](https://user-images.githubusercontent.com/1332279/69025775-b07b2580-0a0b-11ea-9d48-d4a33672b3c0.png)
When I finish submitting a video, whole list becomes duplicated

**Comment by sydneyitguy** [comment]
This happens when I go into "My uploads" or "My votes" menu as well

**Comment by ggomaeng** [comment]
Should be fixed in 1881f010
