### ISSUE TITLE
Color highlight on currently playing video

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#30]
First, I think we better have some highlight on current playing video on the list (maybe ▶️ icon on the list or some color highlight )

![image](https://user-images.githubusercontent.com/1332279/69027052-d48d3580-0a10-11ea-8bcb-431e29d7b08d.png)

**Comment by cyh76507707** [comment]
Zeplin: `tv-main`
Check out this site (how to present "live"): https://music.airfrance.com/en/player
![tv-main](https://user-images.githubusercontent.com/15100667/69325728-83fd1e80-0c42-11ea-9207-86f455b34c1b.png)
