### ISSUE TITLE
Auto play next video

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#32]
Some people would just visit the site on the TV to just turn on popular videos everyday without much attention.

- [x] Currently we just stop play when a video finished, but we need to play the next video.
- [x] If the video is the end of the list, load the next day when user is on daily chart
- [x] If the video is the end of the list, stop playing when user is on "My uploads" or "My votes" menu

**Comment by ggomaeng** [comment]
Must have been removed while refactoring. Reimplemented in e5348865.
