### ISSUE TITLE
Remove unnecessary files and styles

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#34]
It seems the first version (quiz hunt) of the files are still there.

- [x] assets
- [x] codes
- [x] styles

**Comment by sydneyitguy** [comment]
@ggomaeng Seems I cleaned up most stuff, please double check if I did anything wrong or missed something

**Comment by ggomaeng** [comment]
Looks good to me! Thank you for doing this :) -- I was going to nifty things up before launch.
