### ISSUE TITLE
Changes in tags

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#37]
- [x] Tag should have it's own URL: e.g. /tags/games
- [x] Tag should just show all time ranking on that tags (API call without `days_ago`, only `tag` parameter is required. Let's implement pagination later)
- [x] Make the tag on the top left side of the screen clickable
- [x] Remove tag links on the top navigation because it's confusing as tag link shows all-time ranking and distract app's core concept of "daily ranking" (Please confirm if this requires any design changes @cyh76507707)

**Comment by ggomaeng** [comment]
@sydneyitguy I tried calling the api with "tag: gta", and it also returns other videos that doesn't have the "gta" tag.

![image](https://user-images.githubusercontent.com/18402191/69279155-a175ae00-0b98-11ea-972a-80c324a6b600.png)

![image](https://user-images.githubusercontent.com/18402191/69279178-ad617000-0b98-11ea-8597-68a6584d2d6d.png)

**Comment by sydneyitguy** [comment]
Oh the parameter was `tags` with "s". Sorry I mistyped on the content again.. haha
