### ISSUE TITLE
Shows a wrong message on upload menu

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#39]
![image](https://user-images.githubusercontent.com/1332279/69219746-d8f35300-0bb6-11ea-95c1-2bf573ad87e8.png)

**Comment by sydneyitguy** [comment]
"Please join the ranking curation now" -> something like "Share a 😂video you discovered today"

"CHECK NOW" -> "UPLOAD NOW" (go to submit page)

**Comment by sydneyitguy** [comment]
Also.. Shouldn't we change the word "upload" to "share" ?
Because users don't technically "upload" videos on our website.

**Comment by ggomaeng** [comment]
How about "Shared Videos" or "My Shared Videos"?

**Comment by sydneyitguy** [comment]
"Shared Videos" sounds good 👍🏻

**Comment by ggomaeng** [comment]
Should we change "HUNT VIDEO" to "SHARE VIDEO" too then? I feel like new users might be unfamiliar to the term hunt for this platform. What do you think?

**Comment by sydneyitguy** [comment]
SHARE VIDEO sounds better 👍
