### ISSUE TITLE
Tag input interface

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#40]
Can we catch tab or space key to input next hashtag?
it's a bit inconvenient to click "New tag" button every time

**Comment by ggomaeng** [comment]
It handles space key and comma right now. I added the tab in a2dab685.

**Comment by sydneyitguy** [comment]
Can we add "tab" key too?

**Comment by sydneyitguy** [comment]
Not working on mobile some reason

**Comment by ggomaeng** [comment]
I was able to use the space key on my iPhone XS Max. Are you typing in Korean by any chance?

**Comment by ggomaeng** [comment]
Space separator seems to work, but initial focus doesn't seem to work on mobile for some reason

**Comment by sydneyitguy** [comment]
works now
