### ISSUE TITLE
CORS error on youtube video parsing

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#5]
On the first step in the submission page, when I Submit it returns
```
Access to fetch at 'https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=HGLwyUqBV4c&format=json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
error because it tried to fetch the json file from the client.
I don't know how it was working on your end tough..

To fix, I made a wrapper API `/videos/get_info.json` (docs updated too)

Also atm, when the submission failed, the button just remained as "disabled" status, not showing any error and impossible to retry.

![image](https://user-images.githubusercontent.com/1332279/68763274-6389fe80-065b-11ea-9b1a-3e614a28d638.png)

- [ ] CORS error due to API call to youtube.com
- [ ] Error handling on submission

**Comment by ggomaeng** [comment]
@sydneyitguy I get `error: "No video found"` for every video I submit. Could you double check this?
