### ISSUE TITLE
Sentences on login modal

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#50]
![image](https://user-images.githubusercontent.com/1332279/69296578-14416080-0c4f-11ea-9e01-29cb81130949.png)

How about we change the content like:

### Save Your Data Privately
LOL Hunt does not save your upvoting or hunting activities on our server. We use Blockstack,  a revolutionary user authentication and decentralized storage system that gives you full controllability of your data.

**Comment by ggomaeng** [comment]
Sounds good. I will change accordingly.
