### ISSUE TITLE
Loading logo is not vertically centered

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#55]
![012BFECF-D34C-4793-953F-9DD2E7E8E6DA](https://user-images.githubusercontent.com/1332279/69316358-03f3aa80-0c7c-11ea-8b60-cd0d7fa3db69.jpeg)

It looks misaligned with other control buttons.

![image](https://user-images.githubusercontent.com/1332279/69325921-4aea9b80-0c8e-11ea-8319-c01db1e19e9f.png)

It looks better on desktop, but still seems little bit lower than others

**Comment by ggomaeng** [comment]
This could be happening because the hover controls are centered based on height excluding the header, and the LOL logo is centered based on the full height of the screen. I made a lot of css updates, so it might be better on the latest push.

**Comment by ggomaeng** [comment]
Changed from 100vh -> 100%. It should look more aligned now.
