### ISSUE TITLE
Space at the bottom on iPhone

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#62]
![043C7B07-0438-4AB2-9DC7-814D3D7B5C95](https://user-images.githubusercontent.com/1332279/69428376-6039f580-0d74-11ea-8729-23e2f270965b.png)

**Comment by ggomaeng** [comment]
This looks like it was taken on a saved web version from Safari -- am I correct?

**Comment by ggomaeng** [comment]
Should be fixed on 449c2027. It's due to chrome not supporting 100vh. More here: https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser

**Comment by ggomaeng** [comment]
Should be fixed on 98373d33. Tested on mobile chrome and safari.
