### ISSUE TITLE
Vote count doesn't update after voting

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#63]
![image](https://user-images.githubusercontent.com/1332279/69490758-4103ab00-0ecf-11ea-836a-b0b95360094c.png)

It doesn't update on the right panel list after I cast voting.

**Comment by sydneyitguy** [comment]
It happens randomly. Let's dig into the cause when it happens

**Comment by ggomaeng** [comment]
This was happening because likeUnlike function was only modifying the "playlist" array, which is the main playlist used to render on the main page. Shared, voted, tags has its own array, so the vote count wasn't reflected properly. Fixed in 65589f59.
