### ISSUE TITLE
Refresh changes right panel

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#64]
When you're on a video page:
https://lol.hunt.town/standup/yumi-nagashima-best-savage-moments-2018

and refresh the page,
right panel shows #standup tag list.

how about.. using "https://lol.hunt.town/tags/standup/yumi-nagashima-best-savage-moments-2018" url for tags result page instead? normal URL should just show normal right panel (Today's ranking)

**Comment by ggomaeng** [comment]
Now, it only goes to the /tags/ location when:
1. the user manually enters /tags/:tagname in the url
2. user clicks on the tag

and it only loads the tags section if the url starts with /tags/:tagname.

Refreshing on the 1st url you mentioned won't give them the tag results anymore.
