### ISSUE TITLE
Menu button

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#67]
A feedback from @ggomaeng's friend: Menu button looks confusing with Login icon

Let's just change the menu button to the most common one: hamburger

https://jonsuh.com/hamburgers/

I like `Emphatic` animation effect. Tell me your ideas @ggomaeng @cyh76507707

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/69491347-c728de80-0e48-11ea-9653-43a00bfe87fa.png)
![image](https://user-images.githubusercontent.com/18402191/69491349-cbed9280-0e48-11ea-9913-bb3ba85ee680.png)

These two images are different components, so I don't know if animations will work properly in this case. I can change them into hamburger and x button

**Comment by sydneyitguy** [comment]
I guess you can make the sub component only for menu button to solve the issue?

**Comment by ggomaeng** [comment]
![image](https://user-images.githubusercontent.com/18402191/69894758-1ce20880-12d9-11ea-8c92-1a7544ab7fac.png)
![image](https://user-images.githubusercontent.com/18402191/69894760-23708000-12d9-11ea-8f54-ff3d77563b51.png)

How does this look?

**Comment by sydneyitguy** [comment]
I think it's less confusing than the current menu button, but.. not sure.
What do you guys think? @ggomaeng @cyh76507707

**Comment by ggomaeng** [comment]
Or maybe we can place "Hide Ranking" where the product hunt button is.

**Comment by sydneyitguy** [comment]
Oh how about add a theatre mode on the bottom before the full-screen button?
e.g.
![image](https://user-images.githubusercontent.com/1332279/69895347-e952bd00-1370-11ea-81fe-01b0a6be8c47.png)

**Comment by ggomaeng** [comment]
I actually think that's the perfect solution we're looking for.

**Comment by sydneyitguy** [comment]
Yeah let’s do that then
