### ISSUE TITLE
Default - muted

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#7]
Video should be muted by default when people first visit

![image](https://user-images.githubusercontent.com/1332279/68828214-40f1f700-06e8-11ea-860b-9edb6ec6b6dc.png)

This image should show "muted" status properly when it's muted and
if that still doesn't look obvious, we may have to add "Click to unmute" button on the screen

**Comment by ggomaeng** [comment]
So I'm using <Icon type="sound" /> from antd, but unfortunately there is no "muted" type in the icons. Could @cyh76507707 possibly create it?
