### ISSUE TITLE
Infinite scrolling load too many prev days?

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#71]
![image](https://user-images.githubusercontent.com/1332279/69601463-94086a00-1057-11ea-90a5-dfc51eff098e.png)

What's the logic atm?

**Comment by sydneyitguy** [comment]
It still loads 11 days from the first place.

**Comment by ggomaeng** [comment]
Infinite Loading logic updated - dafa7736

1. On first load, it loads last 3 days and populates the list
2. When the scroll reaches the bottom, it loads the last 5 more days from the last day loaded
3. If there are 5 consecutive empty days, it considers the list to be done and doesn't load any more.
