### ISSUE TITLE
Loading screen full screen issue

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/tvhunt-web#73]
![9334BBFB-7CCD-4BD9-9BAF-58C4AF07DB27](https://user-images.githubusercontent.com/1332279/69652702-6ce08580-10b5-11ea-880d-490038db1d52.jpeg)

Still seeing the bottom part cut out.
(works fine one non-full screen mode)
Tested on WebOS tv browser

**Comment by sydneyitguy** [comment]
I guess this issue is because we calculate the screen height on page loading, and it increases when user enters to the full screen mode

**Comment by ggomaeng** [comment]
The noise size is recalculated on page resize. It only seems to happen on WebOS. How do I test on WebOS tv browser?

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/70194968-9baacb80-1747-11ea-9b2d-a42d751c0378.png)
I see the same issue on my Mac - Chrome too.

I guess that resize event doesn't get triggered on entering full-screen mode.
Maybe we should do that on every time the loading screen displayed?

**Comment by ggomaeng** [comment]
Ah, I was able to reproduce it. I misunderstood the fullscreen mode with the theatre mode. I will investigate it 👍
