### ISSUE TITLE
Share button from Youtube

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/tvhunt-web#77]
Once a user clicks the share button from the Youtube view, the default share buttons are overlapped with the upvoting button.

![Screenshot 2019-12-04 14 39 09](https://user-images.githubusercontent.com/15100667/70158797-c21d2800-16af-11ea-93ef-73300f8ad1a5.png)

**Comment by sydneyitguy** [comment]
Can we just disable or hide youtube share button?

**Comment by ggomaeng** [comment]
It's not possible to hide or disable the youtube share button. It's possible to create our custom overlay on top of the share button and make them share our lol.hunt link.

**Comment by sydneyitguy** [comment]
Our custom overlay would be nice 👍🏻
Do we need a design for that? @cyh76507707 @ggomaeng

**Comment by ggomaeng** [comment]
I think I will be okay without it :)

**Comment by sydneyitguy** [comment]
Go for it then 👍🏻
