### ISSUE TITLE
Total video number

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/tvhunt-web#79]
The number of total videos of the day has a bug. It shows only "10" when there are more videos.
![Screenshot 2019-12-07 05 50 05](https://user-images.githubusercontent.com/15100667/70369727-aedba980-18b5-11ea-85b0-ab9d05111839.png)

**Comment by ggomaeng** [comment]
@sydneyitguy 

`total_count` for https://lol-api.hunt.town/videos.json?days_ago=2&top=**true** returns `10`
`total_count` for https://lol-api.hunt.town/videos.json?days_ago=2&top=**false** returns `19`

I think they should return 19 for both cases

**Comment by sydneyitguy** [comment]
Fixed

**Comment by cyh76507707** [comment]
After hunting a new video, the number of videos are massing again. 

![Screenshot 2019-12-10 10 13 09](https://user-images.githubusercontent.com/15100667/70520661-d17bf580-1b35-11ea-9f23-290750ef5d41.png)
